# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: GhupShup Chat-App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}


# backend render run
# install ependance and goes to backend directory
    - name: Backend Dependency
      run: ./backend && npm install

    # create build and run
    - name: Build Backend
      run: ./backend && npm run build --if-present


      # frontend run veercel side
    - name: Frontend Directory
      run: ./frontend && npm install

      # create build and run
    - name: Build Frontend
      run: ./frontend && npm run build --if-present


    
